[SPBU-21.B10] Task 5.1 Мясникова Мария
mawekk/prog_homework pull request #14
Opened 2021-11-15 21:11 UTC by mawekk

2021-12-18 09:16 UTC, ArtyomLobanov requested changes

2021-12-18 09:16 UTC, ArtyomLobanov commented on homework_5/task_1.c
> +                free(pair);
Можно было Pair и по значению передавать. Меньше мороки с очисткой памяти было бы

2021-12-18 09:16 UTC, ArtyomLobanov commented on homework_5/task_1.c
> +    }
```cpp
for (TreeMapIterator iterator = getIterator(tree); getKey(iterator).type != NONE_TYPE; next(&iterator)) 
    fprintf(fileName, "%d %d\n", getInt(getKey(iterator)), getInt(getValue(iterator)));
```

2021-12-18 09:16 UTC, ArtyomLobanov commented on homework_5/task_1.c
> +    deleteTreeMap(tree);
Файлы не закрыли

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +    ValueType keyType;
А зачем вам эти поля?

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +    tree->root = balance(tree->root);
Функция balance восстановит вам баланс только в том случае, когда оба поддерева корня корректно сбалансированы, а их высоты отличаются не более чем на два. При удалении/добавлении вершины мы потенциально ломаем баланс не только корню, но и всем вершинам на пути от корня до удалённой/добавленной вершины.
Функцию balance нужно вызывать на каждом уровне на обратном ходе рекурсии.

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        return findKey(node->leftChild, key, comparator);
Утечка памяти. Очистите память из-под pair, а лучше создавайте pair только в тех случаях, когда он вам пригодится.

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        return true;
```cpp
return pair->key.type != NONE_TYPE;
```

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +    node->leftChild = removeMinimum(node->leftChild);
Родителя node->left тут не надо, случайно, обновить?

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +            return NULL;
free(node);

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +            return left;
free(node);

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        free(node);
А кто высоты пересчитывать будет?

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        free(node);
Этот комментарий ко всей функции, а не к этому if-у

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +            left->parent = parent;
А зачем вам вообще родителя отдельно передавать? Почему node->parent не использовать?

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        if (comparator(bound->key, key) == -1 || comparator(bound->key, root->key) == 1)
Все ключи в левом поддереве должны быть меньше ключа в вершине – это инвариант дерева поиска. Если у вас корректное дерево, то отдельно проверять, что `comparator(bound->key, root->key) == 1` не нужно – это условие никогда не выполнится.

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +    if (bound != NULL)
`if (bound)`

2021-12-18 09:16 UTC, ArtyomLobanov commented on library/tree/tree.c
> +                break;
```cpp
while (node->parent != NULL && node->parent->leftChild != node)
    next = node->parent;
next = node->parent;
```

2021-12-18 19:36 UTC, mawekk commented on library/tree/tree.c
> +    ValueType keyType;
чтобы в дереве хранились ключи и значения одинакового типа

2021-12-19 01:46 UTC, mawekk commented on library/tree/tree.c
> +    ValueType keyType;
похоже я забыла их использовать, ну ладно...

2021-12-19 02:05 UTC, mawekk commented
в выводе дереве первую строку выводит наоборот (вместо "0 3" - "3 0"), потому что функции вызываются в обратном порядке... зачем и почему...
и насчет высот - они же у меня в функции балансировки и пересчитываются, или я что-то не так поняла?

2021-12-21 10:06 UTC, ArtyomLobanov requested changes
Можете подробнее описать вашу проблему с выводом? Я не совсем понял о чём речь.

2021-12-21 10:06 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        insert(node, node->leftChild, key, value, comparator);
![image](https://user-images.githubusercontent.com/9067686/146908972-20a93cd2-9478-45fa-ae8d-24c23067445d.png)
Представьте, что вы сейчас добавляете в серое дерево зелёную вершину. Зёленая вершина – newNode. Вы корректно проставили все ссылки  на родителей/детей, обновили высоты и сейчас собираетесь восстановить баланс. Что вы для этого делаете? Вызываете balance от newNode. Но у newNode даже нет детей. Она гарантированно сбалансированная. Родитель newNode и даже родитель родителя в данном случае также находятся в пределах нормы после добавления вершины, а вот в корне наблюдается дисбаланс –  высота левого поддерева всего 1, а высота правого уже 3. В итоге вы получили некорректное AVL-дерево. Чтобы этого избежать, нужно во всех модифицирующих операциях на обратном пути из рекурсии исправлять баланс вершины, чьи поддеревья изменились.

2021-12-21 10:06 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        updateHeight(node->parent);
Вы не можете сразу проставить корретные высоты при добавлении вершины т.к. дерево ещё может измениться при выходе из рекурсии за счёт поворотов. Уберите отсюда рекурсивный вызов и вызывайте функцию пересчёта высоты адресно при изменении/модификации детей конкретной вершины.

2021-12-21 10:06 UTC, ArtyomLobanov commented on library/tree/tree.c
> +        return balance(min);
Ок, баланс пересчитывает высоты. Но в вашей реализации updateHeight работает рекурсивно и соответственно тратит время прямо пропорциональное глубине вершины. Т.е. на каждом из уровней рекурсии (коих log(n)) вы вызываете функцию, которая раюотает порядка log(n) – а значит общее время работы порядка (log(n))^2, что сводит на нет все плюсы сбалансированно дерева поиска

2021-12-21 15:40 UTC, mawekk commented
насчет вывода: в вашем файле "shop_balance" (вроде бы он так называется) ответ следующий: 
![image](https://user-images.githubusercontent.com/67863401/146957400-d1074900-0d86-4f2f-83b0-a15722994289.png)
а у меня в первой строке выводится "3 0", дальше все сходится

2021-12-24 15:52 UTC, ArtyomLobanov requested changes

2021-12-24 15:52 UTC, ArtyomLobanov commented on library/tree/tree.c
> +    return iterator;
Вы объявили структуру TreeMapIterator  вот так
![image](https://user-images.githubusercontent.com/9067686/147363043-be080ff9-64e0-4872-bf46-18983792cc8b.png)
А значит, при создании сначала нужно передавать вершину, затем ключ и только потом значение. А вы при первом создании передаёте сначала значение, а затем ключ. Из-за этого у вас порядок вывода и неправильный. 
Чтобы в будущем избежать подобных ошибок, можно при создании структуры явно указывать имена полей, которые вы хотите инициализировать
![image](https://user-images.githubusercontent.com/9067686/147363127-defa245f-042d-462f-89fe-2314b027c3b7.png)

2021-12-24 16:00 UTC, mawekk commented on library/tree/tree.c
> +    return iterator;
да, спасибо, я сегодня уже нашла эту ошибку)

2022-04-24 00:11 UTC, closed without merging