[SPBU-21.B10] Task 8.2 Мясникова Мария
mawekk/prog_homework pull request #18
Opened 2021-12-06 22:49 UTC by mawekk

2021-12-07 09:27 UTC, mawekk commented
запуталась с ошибкой, не совсем поняла, как правильно передавать ее в функциях :(

2021-12-11 14:06 UTC, SpirinEgor requested changes
Действительно какая-то путаница в ошибке. Но там вроде бы надо просто if поправить.

2021-12-11 14:06 UTC, SpirinEgor commented on library/DFA/DFA.c
> +            return false;
А я правильно понял, что у тебя `current` отвечает за ошибку и за состояние автомата?
Звучит странно, скорее надо иметь 2 переменных.

2021-12-11 14:06 UTC, SpirinEgor commented on library/DFA/DFA.c
> +            return false;
Причём они у тебя есть вроде как, но проверки странно делаются

2021-12-11 14:06 UTC, SpirinEgor commented on library/DFA/DFA.c
> +    }
А тут точно нет кучи лишних действий? Ты ведь по сути знаешь в каком `transition` ты находишься и тебе только для него надо проверить, можно ли по символу перейти

2021-12-13 14:38 UTC, SpirinEgor requested changes
Надо чутка аккуратнее ошибку обрабатывать. Main можно не трогать, там я для примера написал, что можно делать с ошибкой

2021-12-13 14:38 UTC, SpirinEgor commented on library/DFA/DFA.c
> +    return **error;
А почему тут ошибка возвращается?
Наверное, тут какое-то значение по умолчанию должно возвращаться, типа -1.
Ну и надо ошибку ставить, видимо это должен быть ALPHABET_ERROR. Его скорее надо ставить тут, а не в цикле. А 0 ставить перед return.

2021-12-13 14:38 UTC, SpirinEgor commented on library/DFA/DFA.c
> +            return true;
Тут надо ошибку в 0 выставить перед возвратом

2021-12-13 14:38 UTC, SpirinEgor commented on library/DFA/DFA.c
> +    return false;
А тут надо выставить специальную ошибку. Что в конце не то состояние.

2021-12-13 14:38 UTC, SpirinEgor commented on homework_8/task_2.c
> +        printf("This isn't a number :(\n");
А тут можно смотреть на значение `error` и написать, что же там такого в автомате произошло, что строка не число

2021-12-15 07:23 UTC, SpirinEgor requested changes

2021-12-15 07:23 UTC, SpirinEgor commented on library/DFA/DFA.c
> +#include <malloc.h>
Эх, только хотел зачесть :(
Почему эта либа, а не stdlib.h? Не раз писал, что это специфичная для винды штука и не надо её использовать, иначе мы не сможем запустить ваш код.

2021-12-17 14:07 UTC, mawekk commented on library/DFA/DFA.c
> +#include <malloc.h>
ой, я промахнулась видимо, когда выбирала, откуда импортить :(

2021-12-17 15:21 UTC, SpirinEgor approved these changes

2021-12-17 15:21 UTC, merged