[SPBU-21.B10] Task 2.2 Мясникова Мария
mawekk/prog_homework pull request #7
Opened 2021-10-03 21:41 UTC by mawekk

2021-10-12 06:10 UTC, ArtyomLobanov requested changes
На исправление неделя. Уложитесь – поставлю полный балл

2021-10-12 06:10 UTC, ArtyomLobanov commented on homework_2/task_2.c
> +    int size = 0, numberOfLogs = 0;
Формально говоря, используемый нами стайлгайд такое не запрещает, но вообще объявлять несколько переменных на одной строке – дурной тон. Так тяжелее следить за количеством и изменением переменных + конкретно в C/C++ есть проблема с указателями. В конструкции
```cpp
int* a, b, c;
```
* на самом деле относится к имени переменной т.е. вы объявили один указатель на int и две переменные типа int. И это выглядит контринтуитивно и может сбивать с толку при беглом чтении. Объявить три указателя можно было бы так:
```cpp
int *a, *b, *c;
```
Но лучше в целом избегать таких конструкций. Экономить строки никто не просил.

2021-10-12 06:10 UTC, ArtyomLobanov commented on homework_2/task_2.c
> +    char originalData[size], log[128] = "", firstData[128] = "", secondData[128] = "";
Сколько нужно места, чтобы хранить строку из size символов? Спойлер: size + 1 т.к. строка должна оканчиваться специальным нулевым символом.

2021-10-12 06:10 UTC, ArtyomLobanov commented on homework_2/task_2.c
> +void readFile(FILE* fileName)
FILE* – это файловый дескриптор. Можно было обозвать его file, input и т.д., но имя filename этому типу точно не соответствует.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/DNA.c
> +    makeNewElement(map, dna);
У вас утечка памяти: вы создаёте копию dna здесь, а потом создаёте ещё копию копии в makeNewElement, а память от первой копии не очищаете. Давайте примем за правило, что в makeNewElement вызывается только изнутри структуры и гарантируется, что переданный указатель можно использовать не копируя

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/DNA.c
> +    }
Тут что-то странное написано. Во-первых, удалить часть строки можно за линейное время, а не за квадратное, как у вас. Во-вторых, first указывает куда-то в середину строки. Когда вы обращаетесь к first[strlen(dna) - 1], вы попадаете куда-то далеко за пределы массива. Ну и strlen работает не за 1, а за длинну строки. Т.е. на каждой итерации for-а при проверке условия вы итерируетесь по всей строке.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/DNA.c
> +            first[j] = first[j + 1];
А позицию end вы вообще не искали же? Что здесь происходит?

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +    ListElement* previousElement;
Так, а DNA.c – это кусок какого-то альтернативного решения, заброшенного на полпути да? Удалите его из репозитория тогда

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +    } else if (!list->tail) {
Не правда ли `list->head == NULL` и `list->tail == NULL` случаются только в одном случае (и всегда одновременно) – если список пуст? Тогда нужен один if для пустого списка и один для непустого. А сейчас у вас бага – при добавлении элемента в пустой список не обновляется указатель на хвост.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +    }
Давайте в случае неудачи либо записывать NULL в beginning и ending, либо возвращать false из findFragment.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +            if (strlen(string) == strlen(fragment)) {
strlen итерируется по строке, пока не найдёт нулевой символ. Это долгая операция. Не вызывайте её без острой необходимости. Определить тот факт, что мы только что скопировали последний символ можно проще `if (!fragment[i + 1])`.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +        if (!(strcmp(string, fragment)))
Так, конечно, можно, но это требует выделения дополнительной памяти. Ну и строго говоря, ограничение в 128 символов относится к нашей конкретной задаче, а эта реализация списка символов лежит в папке абсолютно справедливо лежит в папке library и, следовательно, должна быть универсальной. Давайте реализуем функцию match:
```cpp
bool match(Element* start, char* pattern)
{
    Element* current = start;
    char* pointer = pattern;
    while (*pointer && current) {
        if (*pointer != current->symbol) 
            return false;
        pointer++;
        current = current->next;
    }
    return !(*pointer);
}
```
(Конкретно на такой реализации не настаиваю, главное что без использования дополнительной памяти и встроенных функций сравнения строк)

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +void findFragment(List* list, ListElement** beginning, ListElement** ending, char* fragment)
Но вам же нужно будет искать фрагмент не только с начала списка, но и с какого-то места в нём. Скажем, при выполнении команды `DELETE AB CD` для строки `CDABAACDAB` вам нужно будет сначала найти первый фрагмент AB, а затем первый фрагмент `CD`, начинающийся строго после конца найденного AB. Т.е. как-то так `CD[AB]AA[CD]AB`, а не так `[CD][AB]AACDAB`

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +void findFragment(List* list, ListElement** beginning, ListElement** ending, char* fragment)
Поэтому принимать здесь нужно не указатель на list целиком, а указатель на конкретный элемент списка, с которого следует начать поиск.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +    for (int i = 0; i < strlen(fragment); ++i) {
Опять у вас strlen в условии цикла используется :(
```cpp
for (char* pointer = fragment; *pointer; pointer++) { // Пока не встретили нулевой символ = конец строки
    ... // добавляем в список символ, на который указывает pointer
}
```

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +        current = new;
Если current – последний элемент списка, то нужно обновить list->tail

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +        next = element->nextElement;
Если start – первый элемент списка или end – последний, то нужно обновить соответствующие поля в list

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +    findFragment(list, &endBeginning, &endEnding, end);
Вы сейчас можете найти конец в строке раньше, чем начало. Пример: `DELETE AB CD` для строки `CDABAACD`

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +    findFragment(list, &endBeginning, &endEnding, end);
И проверяйте, что фрагменты в принципе нашлись. Даже если вы верите в прямоту моих рук (зря) и уверены, что в тестовом файле нет ошибок, дополнительные проверки всегда могут помочь найти и локализовать баги в вашем коде.

2021-10-12 06:10 UTC, ArtyomLobanov commented on library/list.c
> +}
Забыли освободить память из под самого списка (List)

2021-10-12 06:15 UTC, ArtyomLobanov commented on library/list.c
> +    insertElements(current, fragment);
Кстати говоря, если мы делаем replace от начала строки (`REPLACE ABA CABA` для `ABAFCYGVUIO`), то current у вас будет NULL и insertElements скорее всего упадёт.

2021-10-12 06:17 UTC, ArtyomLobanov commented
Это же вы жаловались на replace? Скорее всего проблема в необновляемых ссылках на голову списка. Если всё исправите, а оно не заработает, пните ещё раз

2021-10-15 22:02 UTC, mawekk commented
пыталась чего-то исправлять, но захотела потестить вывод в файл и, конечно же, все сломалось👍🏻
почему-то выводит 18 строк (хотя операций делает штук 30) и кусок 19 строки :)
что не так - вообще не понимаю (плакать хочется)

2021-10-15 22:11 UTC, ArtyomLobanov commented
Если не ошибаюсь, запись в файл через стандартный fprintf буферизируется т.е. когда вы вызываете fprintf, ваши символы записываются не сразу (запись в файл – долгая операция), а сначала добавляются в буфер в оперативной памяти. Когда буфер заполняется, данные сразу скопом переписываются в файл. Но если программа упадёт раньше, то данные в буфере пропадут. Меньше строк в файле у вас получается скорее всего именно по этой причине. А код сейчас гляну

2021-10-15 22:41 UTC, ArtyomLobanov commented on library/list.c
> +        list->tail->nextElement = NULL;
element->previousElement  и element->nextElement и так равны NULL при создании элемента через makeNewElement

2021-10-15 22:41 UTC, ArtyomLobanov commented on library/list.c
> +    while (element != end->nextElement) {
Вот тут есть проблема. Вот вы дошли до element == end. В цикле вы освобождаете память из-под этого элемента и следующее значение в element. Затем проверяется условие element != end->nextElement, но вот беда: т.к. память на которую ссылается end мы только что освободили, теперь мы читаем данные из освобождённого участка памяти. Это Undefined Behaviour. Конкретно на моём пк ваша программа падала при выполнении первой команды. Если добавить дебаговый вывод, то выглядит это так:
```cpp
void deleteElements(ListElement* start, ListElement* end, List* list)
{
    ListElement* element = start;
    ListElement* next = element->nextElement;
    printf("\n%d\n", end->nextElement);
    while (element != end->nextElement) {
        printf("%d %d %d %c\n", element, end->nextElement, element != end->nextElement, element->symbol);
        element->previousElement->nextElement = next;
        next->previousElement = element->previousElement;
        free(element);
        element = next;
        next = element->nextElement;
    }
```
Вывод:
```
16848528
16845576 16848528 1 A
16845632 16848528 1 A
16846416 16848528 1 C
16846528 16848528 1 C
16846472 16848528 1 A
16848472 16848528 1 G // вот на этой итерации мы освобождаем память из под end
16848528 -572662307 1 C
16848584 -572662307 1 A
16846680 -572662307 1 G
16847240 -572662307 1 C
16848248 -572662307 1 T
```

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +        list->tail->nextElement = NULL;
И вот это обнуление указателя также излишне по тем же причинам

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +void findFragment(ListElement* start, ListElement** beginning, ListElement** ending, char* fragment)
А как понять, что фрагмент найти не удалось? Давайте какой-нибудь механизм для этого придумаем. Я вижу два варианта:

1.  findFragment возвращает тип bool. Если вернула true – значит поиск удался. Если false – не удался.
2. Если поиск не удался, то и в beginning и в ending записывается значение NULL

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +void findFragment(ListElement* start, ListElement** beginning, ListElement** ending, char* fragment)
Теоретически, в тестовом задании такая ситуация возникнуть не должна, но это поможет вам обнаруживать ошибки в программе.

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +    while (element != end->nextElement) {
Самый простой вариант исправления – сохранить end->nextElement в отдельную переменную в начале работы функции:
```cpp
void deleteElements(ListElement* start, ListElement* end, List* list)
{
    ListElement* elementAfter = end->nextElement;
    ...
    while (element != elementAfter) {
        ...
    }
}
```

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +        list->tail = element;
Если end был последним элементом списка, то `end->nextElement == NULL`. Из цикла мы выходим только если `end->nextElement == element`, а значит здесь мы запишем в list->tail значение NULL, хотя по хорошему должны были `start->previousElement` (но помните, что память из-под start вы очищаете в цикле)

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +        current->nextElement = new;
Тут забыли обновить указатель обратный указатель у следующего элемента.
```cpp
current->nextElement->previousElement = new;
```

2021-10-15 23:43 UTC, ArtyomLobanov commented on library/list.c
> +            current = list->head;
Какая-то очень сложная конструкция, а главное довольно странная. Если мы заменяем фрагмент в начале списка, то должны добавлять элементы в голову списка, а не после первого элемента. Лучше обучите insertElements корректно работать, если current == NULL. Пусть добавляет элементы в начало списка.

2021-10-16 02:39 UTC, mawekk commented
нашла проблему: на 7 операции (delete) удаляет все, что нужно, кроме первого символа
до этого все работало хорошо
но почему это происходит для меня загадка

2021-10-16 10:12 UTC, ArtyomLobanov commented on library/list.c
> +        element->previousElement->nextElement = next;
element->previousElement может быть NULL

2021-10-16 10:12 UTC, ArtyomLobanov commented on library/list.c
> +        current = list->head;
Нет, это неправда. Вот у вас есть список
```
        head                     tail
NULL <-> [A] <-> [B] <-> [C] <-> [D] <-> NULL
```
Если вызвать `insertElements(list->head, "EF", list)` или что то же самое `insertElements([A], "EF", list)`, то мы получим такую картину.
```
        head                                       tail
NULL <-> [A] <-> [E]  <-> [F]  <-> [B] <-> [C] <-> [D] <-> NULL
```
А если мы вызываем `insertElements(NULL, "EF", list)`, то хотим получить следующее:
```
        head                                       tail
NULL <-> [E] <-> [F]  <-> [A]  <-> [B] <-> [C] <-> [D] <-> NULL
```

2021-10-16 10:12 UTC, ArtyomLobanov commented on library/list.c
> +        current->nextElement->previousElement = new;
Эту строчку нужно вставить выше – ведь вы уже записали в `current->nextElement` указатель на new. По сути здесь написано `new->previousElement = new`, что, согласитесь, абсурд.

2021-10-16 10:12 UTC, ArtyomLobanov commented on library/list.c
> +        current->nextElement->previousElement = new;
И, кстати, учтите, что `current->nextElement` может быть NULL

2021-10-16 10:12 UTC, ArtyomLobanov commented on library/list.c
> +            printf("ERROR");
В качестве дебага – ок, но потом перенесите весь консольный вывод в main. Пусть deleteFragment возвращает bool или код ошибки, чтобы вызывающий его код мог узнать о возникшей проблеме.

2021-10-16 10:15 UTC, ArtyomLobanov commented
Для сравнения, правильная итоговая последовательность ДНК (т.е. последняя строчка в итоговом файле)
```
GCATGGCAGGGTCATATTGGCGATTAGAGTGCTTCGTTATGCTTCCCCCATCGTCTCGTGTTATCTCCATCCGGAAGTATGGTGTCGCTGGAAAAACTTTGATCAATGGAACTTAACGTAGAGCCTGGGTTGCACTAAAGTAGGATTCGTCGCAAACCCTCAAAACATACGTAGAGCACGCAACCATACCGCGATGGGATCATCGCCGAGCTTTAAATCCATCACCTG
```

2021-10-16 20:54 UTC, ArtyomLobanov approved these changes
Ура! 👍 
В реализации insertElements есть мелкие баги, которые не влияют на работу на тестовом задании т.к. там ни разу не приходится добавлять элементы в начало. Тем не менее, давайте их исправим. Каждый раз смотря на итерацию цикла или на метод целиком, мысленно в голове прокручивайте инварианты вашей структуры данных и убеждайтесь, что ничего не нарушено. Тогда всякие обратные ссылки теряться не будут.

Пока поставлю 2.5 балла из 3. Исправите insertElements – поставлю полный балл.

2021-10-16 20:54 UTC, ArtyomLobanov commented on homework_2/task_2.c
> +    char originalData[size + 1], log[128] = "";
Ну я же уже писал про объявление нескольких переменных на одной строке :(

2021-10-16 20:54 UTC, ArtyomLobanov commented on library/list.c
> +            if (!fragment[i + 1]) {
Можно было проще это реализовать:
```cpp
for (ListElement* suffix = start; suffix; suffix = suffix->next) {
    int i = 0;
    for (ListElement* current = suffix; current && current->symbol == fragment[i]; current = current->next) {
        if (!fragment[++i]) { // Строка template кончилась, все предыдущие символы совпали => нашли искомое
            *beginning = current;
            *ending = element;
            return true;
        }
    }
    // Либо элементы списка кончились раньше, чем искомая строка, либо мы нашли несовпадающий символ
}
return false;
```

2021-10-16 20:54 UTC, ArtyomLobanov commented on library/list.c
> +            new->nextElement = list->head;
Обратную ссылку обновить забыли
`list->head->previousElement = new;`

2021-10-16 20:54 UTC, ArtyomLobanov commented on library/list.c
> +            current->nextElement->previousElement = new;
current->nextElement может быть NULL, если мы добавляем элементы в конец списка

2021-10-16 20:54 UTC, ArtyomLobanov commented on library/list.c
> +                list->head = new;
Почему? Мы же добавляем элементы после current. Если current не NULL, то new никак не может оказаться головой списка

2021-10-16 21:08 UTC, mawekk commented on homework_2/task_2.c
> +    char originalData[size + 1], log[128] = "";
ой, мне казалось, я это исправила :(

2021-10-16 21:38 UTC, ArtyomLobanov commented on library/list.c
> +            list->head->previousElement = new;
list->head может быть NULL

2021-11-03 10:13 UTC, ArtyomLobanov commented on library/list.c
> +                appendElement(list, new->symbol);
Утечка памяти: вы создали уже выделили память на куче под элемент new, но в этой ветке if-ов никак её не используете и указатель на неё не сохраняете. Либо добавьте очищайте память из-под new, если он не пригодился, либо добавляйте элемент в пустой список вручную (благо это делается в две строки), а не вызывайте метод appendElement.
```cpp
list->head = element;
list->tail = element;
```

2021-11-03 10:23 UTC, ArtyomLobanov commented
Ок, зачтено

2021-11-03 10:23 UTC, merged