[SPBU-21.B10] Task 3.1 Мясникова Мария
mawekk/prog_homework pull request #9
Opened 2021-10-15 16:55 UTC by mawekk

2021-10-26 16:51 UTC, SpirinEgor requested changes
Подумай как можно 16 инкапсулировать в binary.c

2021-10-26 16:51 UTC, SpirinEgor commented on homework_3/task_1.c
> +    int* firstBinary = calloc(16, sizeof(int));
Почему 16? Я бы ожидал 8, так как с интом работаешь.

2021-10-26 16:51 UTC, SpirinEgor commented on homework_3/task_1.c
> +    return 0;
А память кто в конце освобождать будет?

2021-10-26 16:51 UTC, SpirinEgor commented on library/binary/binary.c
> +    for (int i = 0; i < 16; i++) {
Много где используется вот эта 16, предлагаю её где-то константой или макросом сделать.

2021-10-26 16:51 UTC, SpirinEgor commented on library/binary/binary.c
> +    for (int i = 0; i < 16; i++) {
Тогда возможно надо будет ещё добавить функцию `createBinary(int num)`. Так как в main эта константа может быть недоступной

2021-10-26 16:51 UTC, SpirinEgor commented on library/binary/binary.c
> +            binary[i] = 0;
`binary[i] = 1 - binary[i]`

2021-10-26 16:51 UTC, SpirinEgor commented on library/binary/binary.c
> +            binary[i] = 1;
`binary[i] = number % 2`

2021-10-26 16:51 UTC, SpirinEgor commented on library/binary/binary.c
> +        int* add = calloc(16, sizeof(int));
Вот тут утечка будет

2021-10-26 16:51 UTC, SpirinEgor commented on library/binary/binary.c
> +            memory = 0;
```c
sum[i] = sum % 2;
memory = sum / 2;
```

2021-10-28 15:49 UTC, SpirinEgor requested changes

2021-10-28 15:49 UTC, SpirinEgor commented on homework_3/task_1.c
> +    int const bitDepth = 16;
Я так и не понял, почему 16 :( Можешь пояснить почему? Просто отпишись в любом удобном тебе месте.

2021-10-28 15:49 UTC, SpirinEgor commented on homework_3/task_1.c
> +    int const bitDepth = 16;
Ну и да, от такой константы, да и в целом интерфейса мало пользы. Раз ты это передаешь аргументом, то это можно менять? А если я вызову `convertToBinary(firstNumber, firstBinary, 2)` оно всё равно будет работать?

2021-10-28 15:49 UTC, SpirinEgor commented on library/binary/binary.c
> +        summa = firstTerm[i] + secondTerm[i] + memory;
prikol 👍 
Может лучше назвать как-то `currentSum` или тип того. Транслит точно не надо.

2021-10-28 15:49 UTC, SpirinEgor commented on library/binary/binary.c
> +            degree = degree * 2;
degree можно поддерживать во внешнем цикле. Просто домножай на 2 на каждой итерации.

2021-10-28 15:51 UTC, mawekk commented on library/binary/binary.c
> +        summa = firstTerm[i] + secondTerm[i] + memory;
ой меня чето переклинило, извиняюсь ахаха

2021-10-28 15:53 UTC, mawekk commented on homework_3/task_1.c
> +    int const bitDepth = 16;
насчет 16 - просто забыла поправить)

2021-11-08 08:37 UTC, SpirinEgor approved these changes

2021-11-08 08:37 UTC, merged